config/routes.rb
# == Route Map (Updated 2014-04-18 22:17)
#
#              Prefix Verb   URI Pattern                         Controller#Action
#               users GET    /users(.:format)                    users#index
#                     POST   /users(.:format)                    users#create
#            new_user GET    /users/new(.:format)                users#new
#           edit_user GET    /users/:id/edit(.:format)           users#edit
#                user GET    /users/:id(.:format)                users#show
#                     PATCH  /users/:id(.:format)                users#update
#                     PUT    /users/:id(.:format)                users#update
#                     DELETE /users/:id(.:format)                users#destroy
#            sessions POST   /sessions(.:format)                 sessions#create
#         new_session GET    /sessions/new(.:format)             sessions#new
#             session DELETE /sessions/:id(.:format)             sessions#destroy
#     password_resets POST   /password_resets(.:format)          password_resets#create
# edit_password_reset GET    /password_resets/:id/edit(.:format) password_resets#edit
#      password_reset PATCH  /password_resets/:id(.:format)      password_resets#update
#                     PUT    /password_resets/:id(.:format)      password_resets#update
#                root GET    /                                   users#index
#              signup GET    /signup(.:format)                   users#new
#              signin GET    /signin(.:format)                   sessions#new
#             signout DELETE /signout(.:format)                  sessions#destroy
#       resque_server        /resque                             Resque::Server
#
require 'resque'
require 'resque_scheduler'
require 'resque_scheduler/server'

WeatherTF::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:create, :edit, :update]

  #should password_resets be limited?? i did

  root 'users#index'


  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'


  mount Resque::Server, at: '/resque'


  get '*path' => redirect('/')  unless Rails.env.development?

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  username                        :string(255)      not null
#  email                           :string(255)
#  crypted_password                :string(255)
#  salt                            :string(255)
#  created_at                      :datetime
#  updated_at                      :datetime
#  phone_number                    :integer
#  carrier                         :string(255)
#  latitude                        :float
#  longitude                       :float
#  digest                          :boolean
#  alert_percent                   :integer
#  address                         :string(255)
#  slug                            :string(255)
#  reset_password_token            :string(255)
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  location_id                     :integer
#

class User < ActiveRecord::Base
  has_many :forecasts, through: :location
  belongs_to :location
  accepts_nested_attributes_for :location
  
  authenticates_with_sorcery!

  validates_presence_of :password, on: :create
  validates_confirmation_of :password
  validates :phone_number, 
    length: { minimum: 10 }, 
    numericality: { only_integer: true },
    allow_blank: true
  validate :email_or_phone_number
  validates_uniqueness_of :email, allow_blank: true
  validate :address_or_coordinates
  
  # before_create :build_location #, :if => :####?
  before_save :create_username
  after_save :build_location


  private

    def email_or_phone_number
      if (email.blank?)
        validates_presence_of :phone_number
      else
        validates_presence_of :email
      end
    end

    def create_username
      if !(email.blank?)
        self.username = email
      else
        self.username = phone_number.to_s
      end
    end

    def build_location
      if (!latitude.blank? and !longitude.blank?)
        Location.create(
          user_id: self.id,
          longitude: self.longitude,
          latitude: self.latitude,
          address: self.address)
        # User.build_location(
        #   longitude: self.longitude,
        #   latitude: self.latitude)
      elsif !(address.blank?)
        Location.create(
          user_id: self.id,
          address: self.address)
        # User.build_location(address: self.address)    
      end

    end

    def address_or_coordinates
      if (latitude.blank? or longitude.blank?)
        validates_presence_of :address
      else
        validates_presence_of :latitude, numericality: true
        validates_presence_of :longitude, numericality: true
      end
    end


end

app/controllers/users_controller.rb
require "message_workers"
require "forecast_workers"

class UsersController < ApplicationController

  before_filter :correct_user, 
    only: [:show, :edit, :update, :delete]

  respond_to :js, :html

  rescue_from ActiveRecord::RecordNotFound do
    # whats all this then? 
  end


  def index
    @user = User.new
  end

  def show
    @forecasts = @user.forecasts
    @location = @user.location
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      begin
        Resque.enqueue(WelcomeEmail, @user.id)
        Resque.enqueue(CurrentForecast, @user.id)
      rescue Exception => e
        # some alert: "we'll email you later"
      end
      flash[:notice] = "welcome"
      redirect_to user_path(@user) 
    else
      @user.errors.full_messages.each do |message|
        flash[:alert] = message
      end

      redirect_to root_path
      # TODO 
      # drop-down the sign-up modal automatically, showing errors
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to :back, notice: "updated"
    else
      render :edit, alert: "error!"
    end
  end

  def destroy
  end


  def sms

    respond_to do |format|
      format.js
    end

    # TelAPI method
    request_data = { :To => current_user.phone_number, :Body => "Hello from WeatherTF", :Token => ENV['TELAPI_TOKEN'] }
    Thread.new { r = HTTParty.post("https://heroku.telapi.com/send_sms", :body => request_data) }.join
    puts "TELAPI response: #{r}"

    #if UserMailer.update_text(current_user).deliver
    #  flash[:notice] = "msg sent"
    #else
    #  flash[:alert] = "msg sending error"
    #end
  end


  private

    def user_params
      params.require(:user).permit(:email, :phone_number, :carrier, :address,
        :password, :password_confirmation, :latitude, :longitude, :digest, :alert_percent)
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user == @user then
        redirect_to root_path, alert: "please log in."
      end
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
	<%= form_for @user, html: {class: "custom"} do |f| %>
		<div class="small-6 columns">

			<div class="row collapse">
				<div class="small-4 columns">
					<span class="prefix">username</span>
				</div>
				<div class="small-8 columns">
					<%= f.text_field :username %>
				</div>
			</div>

			<div class="row collapse">
				<div class="small-4 columns">
					<span class="prefix">email</span>
				</div>
				<div class="small-8 columns">
					<%= f.text_field :email %>
				</div>
			</div>
			<br>

			<div class="row collapse">
				<div class="small-4 columns">
					<span class="prefix">phone #</span>
				</div>
				<div class="small-8 columns">
					<%= f.telephone_field :phone_number %>
				</div>
			</div>

			<div class="row collapse">
				<div class="small-4 columns">
					<span class="prefix">
						Carrier
					</span>
				</div>
				<div class="small-8 columns">
					<%= f.select :carrier, [["choose your mobile carrier"],["Bell"],["Telus"],["Rogers"],["Fido"],["Koodo"],["Wind"]], class: "select"%>
				</div>
			</div>
			<br>
			<%= submit_tag 'find my location', :type => 'button', class:"button", id:"find_location" %>

			<!-- %= f.text_area :address %> -->

			<div class="row collapse">
				<div class="small-6 columns">
					<span class="prefix">
						<%= f.label "longitude" %>
					</span>
				</div>
				<div class="small-6 columns">
					<%= f.telephone_field :longitude %>
				</div>
			</div>

			<div class="row collapse">
				<div class="small-6 columns">
					<span class="prefix">
						<%= f.label "latitude" %>
					</span>
				</div>
				<div class="small-6 columns">
					<%= f.telephone_field :latitude %>
				</div>
			</div>
		</div>

		<div class="small-6 columns">

			<div class="row collapse">
				<div class="small-5 columns">
					<span class="prefix">password</span>
				</div>
				<div class="small-7 columns">
					<%= f.password_field :password %>
				</div>
			</div>

			<div class="row collapse">
				<div class="small-5 columns">
					<span class="prefix">confirm to change</span>
				</div>
				<div class="small-7 columns">
					<%= f.password_field :password_confirmation %>
				</div>
			</div>
			<br>

			<%= f.submit "save changes", class: "button" %>

			<%= link_to "log out.", session_path, class: "button alert", method: :delete, confirm: 'yea?'%>
		</div>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="large-4 columns push-4" id="description">
		<br>
		<h1>WeatherTF</h1>
		<br>
		<h2>
			<small>weather alerts by sms</small>
		</h2>
		<button class="success" data-reveal-id="signup">sign up</button>
		<button data-reveal-id="login">log in</button>
		<br>
		<br>
	</div>
</div>

<!--  sign-up form  -->	
<div id="signup" class="reveal-modal small" data-reveal>
	<div class="row">
		<div class="small-12 columns">
			
			<%= render template: "users/forms/signup_form" %>	

		</div>
	</div>
</div>

<!--  login form    -->
<div id="login" class="reveal-modal small" data-reveal>
	<div class="row">
		<div class="small-12 columns">


			<%= render template: "users/forms/login_form" %>
		
		</div>
	</div>
</div>

app/views/users/login_form.html.erb
<!-- login_form.html.erb -->

<%= form_tag sessions_path do %>
	<div class="row collapse">
		<div class="large-4 columns">
			<span class="prefix">username</span>
		</div>
		<div class="large-8 columns">
			<%=  text_field_tag :username, params[:username] %>
		</div>
	</div>
	<div class="row collapse">
		<div class="large-4 columns">
			<span class="prefix">password</span>
		</div>
		<div class="large-8 columns">
			<%= password_field_tag :password %>
		</div>
	</div>
	<%= submit_tag "login", class:"button large-12 columns" %>
<% end %>

app/views/users/mail_settings.html.erb
<div>
	<p><%= current_user.username %> | <%= number_to_phone(current_user.phone_number) %></p>
</div>

<div class="row">
	<!--<div class="large-6 columns">-->
		<!--<p>A Digest of hourly weather for the whole day will be sent every morning</p>-->
		<!--<p>Specify how likely rain should be before you are notified.</p>-->
	<!--</div>-->

	<!--<%= form_for @user, html: {class: "custom"} do |f| %>-->
		<!--<div class="large-6 columns">-->
			<!--&lt;!&ndash;<%= f.check_box :digest %>&ndash;&gt;-->
			<!--&lt;!&ndash;<%= f.label "morning_digest" %>&ndash;&gt;-->
			<!--<br>-->
			<!--<br>-->
			<!--<br>-->
			<!--<div class="large-7 columns">-->
				<!--<div class="row collapse">-->
					<!--<div class="large-3 columns">-->
						<!--<span class="prefix">%</span>-->
					<!--</div>-->
					<!--<div class="large-6 pull-3 columns">-->
						<!--<%= f.select :alert_percent, [["30"],["40"],["50"],["60"]], class: "select"%>-->
					<!--</div>-->
				<!--</div>-->
			<!--</div>-->
		<!--</div>-->
		<!--<br>-->
		<!--<%= f.submit "update", class: "button" %>-->
	<!--<% end %>-->

    <div class="large-6 columns">
      Check that your phone can receive texts from WeatherTF
    </div>
    <div class="large-6 columns">
      <%= link_to  "text me now", sms_path, :method => :put, remote: true, class: "button textnow" %>
    </div>



</div>

app/views/users/new.html.erb
<!-- users whose create from the modal on index are currently sent back there -->
<!-- nobody should end up here -->

<!-- 
<div class="row">
	<div class="large-6 push-3 columns" id="new_form">

		<br>
		<%= render template: 'users/signup_form' %>		

	</div>
</div>
 -->

app/views/users/show.html.erb
<% provide(:title, "Local") %>

<div class="row large-10 push-1 columns">
	<dl class="tabs" data-tab>
		<dd class="active"><a href="#panel2-1">Forecasts</a></dd>
		<dd><a href="#panel2-2">My Account</a></dd>
	</dl>
	<div class=" panel">
		
		<p>
			<%= current_user.username %> | phone: <%= number_to_phone(current_user.phone_number) %>
		</p>

		<div class="tabs-content">
			<div class="content active" id="panel2-1">
				<div>
					<table>
						<thead>
							<tr>
								<th>Time</th>
								<th>Summary</th>
								<th>precipitation Probability</th>
								<th>precipitation Type</th>
								<th>precipitation intensity</th>
								<th>temperature</th>
								<th>humidity</th>
								<th>visibility</th>
<!-- 								<th>latitude</th>
								<th>longitude</th> -->
							</tr>
						</thead>
						<tbody>
							<%= render partial: "layouts/forecast", collection: @forecasts %>
						</tbody>
					</table>
				</div>	
			</div>
			<div class="content" id="panel2-2">
				<%= render template: 'users/edit' %>
			</div>
			<div class="content" id="panel2-3">
				<p>Third panel content goes here...</p>
			</div>
			<div class="content" id="panel2-4">
				<p>Fourth panel content goes here...</p>
		  </div>
		</div>



		</div>

	</div>
</div>

app/views/users/signup_form.html.erb
<!-- _signup_form.html.erb -->

<%= form_for @user, html: {class: "custom"} do |f| %>

	<div class="row collapse">
		<div class="large-4 columns">
			<span class="prefix">email</span>
		</div>
		<div class="large-8 columns">
			<%= f.text_field :email %>
		</div>
	</div>
	<br>

	<div class="row collapse">
		<div class="large-4 columns">
			<span class="prefix">phone #</span>
		</div>
		<div class="large-8 columns">
			<%= f.telephone_field :phone_number %>
		</div>
	</div>

	<%= f.select :carrier, [["choose your mobile carrier"],["Bell"],["Telus"],["Rogers"],["Fido"],["Koodo"],["Wind"]], class: "select"%>
	<br>

	<div class="row collapse">
		<div class="large-4 columns">
			<span class="prefix">password</span>
		</div>
		<div class="large-8 columns">
			<%= f.text_field :password %>
		</div>
	</div>

	<div class="row collapse">
		<div class="large-4 columns">
			<span class="prefix">again to confirm</span>
		</div>
		<div class="large-8 columns">
			<%= f.text_field :password_confirmation %>
		</div>
	</div>
	<br>

	<div id="location_zone">

		<!-- find location button and field for city to be filled by js
		<div class="row collapse">
			<div class="large-6 columns">
				<%= submit_tag 'find my location', type:'button', class:"button secondary", id:"find_location" %>
			</div>
			<div class="large-6 columns">
				<!-- insert the return value from geocoder here? -->
			</div>
		</div>

			<!-- longitude and latitude filled by js -->
			<div class="row collapse">

				<div class="large-3 columns">
					<span class="prefix">
						<%= f.label "longitude" %>
					</span>
				</div>
				<div class="large-3 columns">
					<%= f.telephone_field :longitude %>
				</div>

				<div class="large-3 columns">
					<span class="prefix">
						<%= f.label "latitude" %>
					</span>
				</div>
				<div class="large-3 columns">
					<%= f.telephone_field :latitude %>
				</div>

			</div>

	</div> <!-- end of location_zone -->
	<br>
	<%= f.submit "sign me up", class: "button success expand" %>
	<!-- <button class="small">actually no thanks</button> -->
<!-- it'd be nice if the no thanks button could take people to somewhere else -->
<!-- maybe it could say 'too hungry for this now' and redirect to verdigris -->
<% end %>